# This is a basic workflow to help you get started with Actions

name: Build_And_Deploy_To_Azure
env:
  BASE_URL: https://dabu-partsunlimited{0}.azurewebsites.net/
  Artifact_Name: PartsUnlimited
  Azure_Resource_Group: dabu-PartsUnlimited
  SQL_Server_Name: dabu-PartsUnlimited
  Website_Name: dabu-PartsUnlimited
  Hosting_Plan_Name: dabu-PartsUnlimited
  TAG_CICD_Engine_Name: GitHub Actions

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a multiple jobs: "CI", "Dev", "QA", "Prod"
###################################################################
# CI Stage                                                        #
###################################################################
  CI:
    # The type of runner that the job will run on
    runs-on: windows-2019
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

     # Validate the ARM Template
      - name: "Validate ARM Template"
        uses: azure/arm-deploy@v1
        id: ValidateARMTemplate
        with:
         subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         resourceGroupName: ${{ env.Azure_Resource_Group }}
         template: PartsUnlimited-aspnet45/env/PartsUnlimitedEnv/Templates/FullEnvironmentSetupMerged.json
         parameters: WebsiteName=${{ env.Website_Name }} PUL_ServerName=${{ env.SQL_Server_Name }} PUL_HostingPlanName=${{ env.Hosting_Plan_Name }} CICDEngineName="${{ env.TAG_CICD_Engine_Name }}
         deploymentMode: Validate
         deploymentName: PartsUnlimited from GitHub Actions

     # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo This is the build!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Azure logout
        run: |
          az logout

  Dev:
    if: contains(github.event_name, 'push')
    
    # The type of runner that the job will run on
    runs-on: windows-2019
    env:
      ENV_NAME: -dev 

    # Steps represent a sequence of tasks that will be executed as part of the job
    environment:
      name: Dev
      url: https://dabu-partsunlimited-dev.azurewebsites.net/ 

    needs: CI
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo 'This is Dev!'
        
      - name: Azure logout
        run: |
          az logout

  QA:
    if: contains(github.event_name, 'push')
    
    # The type of runner that the job will run on
    runs-on: windows-2019
    env:
      ENV_NAME: -qa
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    environment:
      name: QA
      url: https://dabu-partsunlimited-qa.azurewebsites.net/ 

    needs: Dev
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo 'This is QA!'

      - name: Azure logout
        run: |
          az logout

  Production:
    if: contains(github.event_name, 'push')
    
    # The type of runner that the job will run on
    runs-on: windows-2019
    env:
      ENV_NAME: ${{null}} 

    # Steps represent a sequence of tasks that will be executed as part of the job
    environment:
      name: Production
      url: https://dabu-partsunlimited.azurewebsites.net/ 

    needs: QA
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo 'This is Production!'

      - name: Azure logout
        run: |
          az logout
