# This is a basic workflow to help you get started with Actions

name: Build_And_Deploy_To_Azure
env:
  BASE_URL: https://dabu-partsunlimited{0}.azurewebsites.net/ 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a multiple jobs: "CI", "Dev", "QA", "Prod"
###################################################################
# CI Stage                                                        #
###################################################################
  CI:
    # The type of runner that the job will run on
    runs-on: windows-2019
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo This is the build!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  Dev:
    if: contains(github.event_name, 'push')
    
    # The type of runner that the job will run on
    runs-on: windows-2019
    env:
      ENV_NAME: -dev 
      ENV_URL: format('https://dabu-partsunlimited{0}.azurewebsites.net/', ${{ env.ENV_NAME }})

    # Steps represent a sequence of tasks that will be executed as part of the job
    environment:
      name: Dev
      url: ${{env.ENV_URL}}

    needs: CI
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo 'This is Dev!'

  QA:
    if: contains(github.event_name, 'push')
    
    # The type of runner that the job will run on
    runs-on: windows-2019
    env:
      ENV_NAME: -qa
      ENV_URL: format('https://dabu-partsunlimited{0}.azurewebsites.net/', ${{ env.ENV_NAME }})
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    environment:
      name: QA
      url: ${{env.ENV_URL}}

    needs: Dev
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo 'This is QA!'

  Production:
    if: contains(github.event_name, 'push')
    
    # The type of runner that the job will run on
    runs-on: windows-2019
    env:
      ENV_NAME: ${{null}} 
      ENV_URL: format('https://dabu-partsunlimited{0}.azurewebsites.net/', ${{ env.ENV_NAME }})

    # Steps represent a sequence of tasks that will be executed as part of the job
    environment:
      name: Production
      url: ${{env.ENV_URL}}

    needs: QA
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo 'This is Production!'
